Task_2_1_1
PalkinEgor/OOP pull request #10
Opened 2024-02-10 19:21 UTC by PalkinEgor

2024-02-11 06:46 UTC, galinabykova requested changes

2024-02-11 06:46 UTC, galinabykova commented on Task_2_1_1/src/main/java/ru/nsu/palkin/SequntialExecution.java
> +                }
вот этот код (строчки 27-30) почти идентично повторяется три раза. Такое дублирование не самого просто кода не очень хорошо.

2024-02-11 06:46 UTC, galinabykova commented on Task_2_1_1/src/main/java/ru/nsu/palkin/ParallelExecution.java
> +        private boolean result = false;
вот эта переменная должна быть volatile
![image](https://github.com/PalkinEgor/OOP/assets/86754545/a87b70ca-55c4-4854-8970-6b3585354d50)
В целях повышения эффективности работы, спецификации языка Java позволяет JRE сохранять локальную копию переменной в каждом потоке, который ссылается на нее. Можно считать эти «внутрипоточные» копии переменных похожими на кэш, помогающий избежать проверки главной памяти каждый раз, когда требуется доступ к значению переменной.
(https://habr.com/ru/articles/108016/)

ещё вот тут можно почитать
https://www.baeldung.com/java-volatile-variables-thread-safety

2024-02-11 06:46 UTC, galinabykova commented on Task_2_1_1/src/main/java/ru/nsu/palkin/SequntialExecution.java
> +                }
например, у тебя сейчас любое отрицательное число будет воспринять это функцией, как простое. Если захочешь поменять эту логику, придётся три раза код менять, где-то можно забыть

2024-02-11 06:46 UTC, galinabykova commented on Task_2_1_1/src/test/java/ru/nsu/palkin/MainTest.java
хочется больше тестов, например, тесты с разным числом потоков для ParallelExecution, тест, когда чисел меньше, чем потоков и т.д. Подумай над тем, какие тесты тебе ещё нужны, и реализуй их. 

На всякий случай (вдруг ты не заметил) проговорю, что, если сделаешь один интерфейс для всех задач, можно сделать для них единые тесты через Provider (как в моём примере). Делать это необязятельно, но полезно знать о такой возможности.

2024-02-11 06:46 UTC, galinabykova commented on Task_2_1_1/times.png
а сколько у тебя ядер на машине, где ты тестировал?

2024-02-17 11:33 UTC, PalkinEgor commented on Task_2_1_1/times.png
Ryzen 5 5500U, 6 ядер, 12 потоков

2024-02-17 12:52 UTC, galinabykova requested changes

2024-02-17 12:52 UTC, galinabykova commented on Task_2_1_1/src/main/java/ru/nsu/palkin/ParallelExecution.java
> +        private volatile boolean result = false;
прошу прощения, я тебя тут ужаснейшим образом обманула. Так как ты читаешь эту переменную после join, тебе здесь не нужен volatile. 
https://docs.oracle.com/javase/tutorial/essential/concurrency/memconsist.html
(важен последний абзац, но лучше прочесть всё)

2024-02-17 12:52 UTC, galinabykova commented on Task_2_1_1/src/test/java/ru/nsu/palkin/MainTest.java
> +        }
вот этот код (20-26) у тебя дублируется, может вынести его в отдельную функцию?

2024-02-18 06:19 UTC, galinabykova approved these changes

2024-02-18 09:29 UTC, merged