Task_2_2_1
PalkinEgor/OOP pull request #12
Opened 2024-04-09 04:55 UTC by PalkinEgor

пока без использования json, но обязательно будет

2024-04-09 10:25 UTC, galinabykova requested changes
жду ещё json и логгирование)

2024-04-09 10:25 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/palkin/MyBlockingQueue.java
> +    public synchronized int size() {
вот этот метод может наврать пользователю, нужно предупредить его об этом хотя бы в документации и названии метода или в идеале придумать API без таких ненадёжных методов)

2024-04-09 10:25 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/palkin/MyBlockingQueue.java
> +    public synchronized void remove(T object) {
у тебя остальные методы синхронизируются по lock, а вот это по всему объекту

2024-04-09 10:25 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/palkin/Courier.java
> +                    orders[i] = vault.get();
если я правильно поняла, может произойти такая ситуация:
1. у курьера в сумке три пиццы, он ждёт 4-ю
2. пиццерия останавливается и останавливает курьера
3. курьер идёт домой, съедая все заказы в сумке)

2024-04-09 10:25 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/palkin/Order.java
> +    public boolean equals(Object object) {
hashcode...

2024-04-09 10:25 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/palkin/Pizzeria.java
> +        while (this.remainingOrders.size() != 0) ;
тут все заказы, пришедшие до закрытия пиццерию готовятся и доставляются? (уточняю)

2024-04-09 10:26 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/palkin/Courier.java
> +                    orders[i] = vault.get();
а, у тебя пиццерия не останавливается, пока все заказы не доставятся

2024-04-12 14:37 UTC, PalkinEgor commented on Task_2_2_1/src/main/java/ru/nsu/palkin/Pizzeria.java
> +        while (this.remainingOrders.size() != 0) ;
да, так и есть

2024-04-12 14:40 UTC, PalkinEgor commented on Task_2_2_1/src/main/java/ru/nsu/palkin/MyBlockingQueue.java
> +    public synchronized int size() {
А что значит наврать пользователю?

2024-04-12 14:52 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/palkin/MyBlockingQueue.java
> +    public synchronized int size() {
нуу, не совсем наврать) Я про такую ситуацию:
пользователь пишет что-то вроде a = q.size();
size возвращает значение, но пока оно ещё не сохранилось в a
другой поток добавляет элемент в очередь
в а сохраняется устаревшее значение

2024-04-13 08:46 UTC, galinabykova requested changes
не забудь добавить png)

2024-04-13 08:46 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/palkin/Pizzeria.java
> +        }
кажется, это спинлок, если да, от него надо избавиться

2024-04-13 08:46 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/palkin/Pizzeria.java
> +        }
например, заменить на что-то блокирующееся, пока очередь не опустеет

2024-04-13 08:46 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/palkin/Pizzeria.java
> +    private Thread addOrderTask() {
мне кажется, что пиццерия должна предоставлять метод для добавления заказа, а не делать заказы сама себе) круто, что ты нагружаешь свою пиццерию, но мне кажется, это лучше сделать в другом классе (может даже в тестах), чтобы была возможность потестить какие-то особенные случаи в пиццерии (в середине дня кончились заказы, а потом пришли новые и т.д.)

2024-04-13 08:46 UTC, galinabykova commented on Task_2_2_1/src/test/java/ru/nsu/palkin/MainTest.java
хочется ещё тестиков (на отдельные компоненты, Baker и т.д. или на особые случаи в пиццерии)

2024-04-15 03:40 UTC, galinabykova requested changes
не забудь UML

2024-04-15 03:40 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/palkin/Pizzeria.java
> +            }
кажется, это всё ещё спинлок... можно в очереди сделать метод заснуть, пока не опустеет. Кажется, только очередь знает, когда она станет пустой

2024-04-15 03:40 UTC, galinabykova commented on Task_2_2_1/src/test/java/ru/nsu/palkin/MainTest.java
разбей, пожалуйста, на классы. И ещё хочется тест (кажется, такого нет), в котором мы создаём ситуацию, когда в середине дня заказов нет, а вечером появляются (чтобы проверить, что все потоки блокируются, как надо, можно с помощью слипов сделать)

2024-04-15 06:13 UTC, PalkinEgor commented on Task_2_2_1/src/test/java/ru/nsu/palkin/MainTest.java
А что надо разбить на классы?

2024-04-15 06:15 UTC, galinabykova commented on Task_2_2_1/src/test/java/ru/nsu/palkin/MainTest.java
тесты, что в отдельном классе были тесты для пиццерии, отдельно для очереди

2024-04-15 15:54 UTC, galinabykova approved these changes

2024-04-15 15:54 UTC, galinabykova commented on Task_2_2_1/src/main/java/ru/nsu/palkin/MyBlockingQueue.java
> +    public void check() throws InterruptedException {
не очень информативное название)

2024-04-15 16:47 UTC, merged