Task_2_3_1
PalkinEgor/OOP pull request #13
Opened 2024-04-30 20:08 UTC by PalkinEgor

very raw version

2024-05-02 05:15 UTC, galinabykova requested changes
Жду в ближайшее время версии с разделением бизнес-логики и представления. Напиши, какой паттерн используешь и покрой бизнес-логику тестами

2024-05-02 05:15 UTC, galinabykova commented on Task_2_3_1/src/main/resources/ru/nsu/palkin/task_2_3_1/hello-view.fxml
О, кажется, это файл из какого-то популярного гайда, видела его несколько раз) (это хорошо, что разбираетесь на примерчиках)

2024-05-07 04:56 UTC, PalkinEgor commented
Паттерн MVC

2024-05-07 07:23 UTC, galinabykova requested changes
хорошая структура, всё чётенько по MVC) добавь больше тестиков, исправь замечания reviewdog

2024-05-07 07:23 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/palkin/Model/Game.java
> +    private void foodChecker() {
мне кажется, это название не совсем описывает всё, что ты тут делаешь. По нему вообще непонятно, что тут добавляется новая еда

2024-05-07 07:23 UTC, galinabykova commented on Task_2_3_1/src/main/java/ru/nsu/palkin/Model/Game.java
> +    private void moveSnake() {
мне кажется, этот метод можно перенести в змейку: ты тут не используешь ничего, кроме this.direction  и пишешь много громоздких this.snake.getSnake(). И, кажется, что этот метод относится только к ней

2024-05-07 16:16 UTC, galinabykova approved these changes

2024-05-07 16:16 UTC, galinabykova commented on Task_2_3_1/src/test/java/ru/nsu/palkin/GameTest.java
> +        Method method = Game.class.getDeclaredMethod("getBadPoints");
Ооо, сильно

2024-05-07 16:16 UTC, galinabykova commented on Task_2_3_1/src/test/java/ru/nsu/palkin/GameTest.java
> +        Method method = Game.class.getDeclaredMethod("getBadPoints");
но немного странно)

2024-05-07 16:16 UTC, galinabykova commented on Task_2_3_1/src/test/java/ru/nsu/palkin/GameTest.java
> +        Method method = Game.class.getDeclaredMethod("getBadPoints");
против тестирования приватных методов есть такой довод, что это детали реализации, которые могут меняться по своему контракту. А если такое часто происходит, придётся тратить большие ресурсы на поддержку тестов

2024-05-07 16:18 UTC, merged