Task_1_2_1
PalkinEgor/OOP pull request #4
Opened 2023-10-11 09:58 UTC by PalkinEgor

2023-10-11 16:52 UTC, galinabykova requested changes
на мягкий дедлайн добавь тесты, также не забудь исправить замечания reviewdog

2023-10-11 16:52 UTC, galinabykova commented on Task_1_2_1/src/test/java/ru/nsu/palkin/MainTest.java
> +    public void exampleTest() {
не забудь тестики для мягкого дедлайна

2023-10-11 16:52 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/palkin/Tree.java
> +public class Tree<T> {
у тебя должен быть класс, наследующий интерфейс Iterable, обычно это сама коллекция, но тут возможны вариации.

2023-10-11 16:52 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/palkin/Tree.java
> +    public ArrayList<Tree<T>> getBfsList() {
тебе нужно не просто возвращать список элементов в порядке обхода, тебе нужно предоставить пользователю возможность итерирования. Скорее всего, у тебя должен быть некоторый BfsIterator и DfsIterator, с помощью которых можно будет итерироваться в ширину или в глубину. То есть пользователь сможет написать что-то вроде

`for (var elem : BfsIterableImpl) {
     System.out.println(elem)
}`

2023-10-16 05:44 UTC, galinabykova requested changes

2023-10-16 05:44 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/palkin/Tree.java
> +public class Tree<T> implements Iterable<Tree<T>> {
почему ты решил итерироваться по деревьям, а не по элементам?

2023-10-16 05:44 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/palkin/Tree.java
> +                throw new ConcurrentModificationException();
опиши, как у тебя происходит отлов ConcurrentModificationException

2023-10-16 05:44 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/palkin/Tree.java
> +         * @return возвращает значение true или false
в спецификации лучше описать, когда метод бросает ConcurrentModificationException

2023-10-16 05:44 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/palkin/Tree.java
> +    public boolean equals(Object obj) {
опиши в спецификации, что такое равные деревья в твоей реализации

2023-10-16 05:44 UTC, galinabykova commented on Task_1_2_1/src/test/java/ru/nsu/palkin/MainTest.java
сделай, пожалуйста, отдельный тест на remove. При поддержании кода будет сложно отловить новый ошибки в remove

2023-10-16 08:10 UTC, PalkinEgor commented on Task_1_2_1/src/main/java/ru/nsu/palkin/Tree.java
> +public class Tree<T> implements Iterable<Tree<T>> {
Допустим наш класс будет расширяться и приобретать поля с новой информацией, то при наличии соответствующих getterов или если поля будут с модификатором доступа public, то во время итерирования по дереву мы будем иметь доступ к этим полям.

2023-10-16 08:23 UTC, PalkinEgor commented on Task_1_2_1/src/main/java/ru/nsu/palkin/Tree.java
> +                throw new ConcurrentModificationException();
У дерева есть поле modificationCount, которое показывает количество изменений в дереве. У итераторов есть поле expectedModificationCount, которое хранит количество изменений в дереве на момент создание экземпляра итератора, затем на каждой проверке в методе hasNext проверяется на совпадение modificationCount и expectedModificationCount, то есть не изменялось ли кол-во изменений в дереве во время итерации по нему.
О том как изменяется modificationCount, при любой модификации дерева (добавление ребенка или удаление элемента), изменяется счетчик модификаций у конкретного узла к которому применялся метод, так и у всех его предков для поддержания кол-во изменений в дереве.

2023-10-16 15:28 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/palkin/Tree.java
> +                throw new ConcurrentModificationException();
счётчики деревьев-детей и дерева-родителя связаны? До начала итерирования они равны?

2023-10-16 15:30 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/palkin/Tree.java
> +public class Tree<T> implements Iterable<Tree<T>> {
не сможет ли пользователь, получив доступ ко всем поддеревьям, как-то поломать счётчики модификаций?

2023-10-16 15:31 UTC, galinabykova requested changes
reviewdog

2023-10-17 03:15 UTC, PalkinEgor commented on Task_1_2_1/src/main/java/ru/nsu/palkin/Tree.java
> +public class Tree<T> implements Iterable<Tree<T>> {
Нет не сможет, так как список детей приватное поле и счетчик модификаций тоже приватное, а при любом изменении выкинется исключение

2023-10-17 03:21 UTC, PalkinEgor commented on Task_1_2_1/src/main/java/ru/nsu/palkin/Tree.java
> +                throw new ConcurrentModificationException();
На начало итерирования счетчики у родителя и ребенка не обязательно должны быть равны, ведь мы запоминаем счетчик модификаций только у дерева с которого начали обход, а затем счетчики ребенка и родителя поддерживаются и изменяются вместе

2023-10-17 03:52 UTC, galinabykova approved these changes

2023-10-17 15:23 UTC, merged