Task_1_2_2
PalkinEgor/OOP pull request #5
Opened 2023-10-22 08:24 UTC by PalkinEgor

2023-10-23 05:10 UTC, galinabykova requested changes

2023-10-23 05:10 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/Graphable.java
> +    StringBuilder shortestPaths(T vert);
это метод не должен быть в этом интерфейсе. 
В этой задаче мы разделяем алгоритмы и представления графа. Основная идея в том, чтобы можно было один раз написать алгоритм, а потом вызывать его для объектов разных представлений графа.
То есть твой алгоритм поиска кратчайших расстояний не должен ничего знать про конкретное представление графа. Всё, что он знает, о переданном ему объекте - то, что он реализует методы интерфейса Graphable. То есть этот метод будет где-то в другом классе, будет принимать на вход Graphable и вершину и будет достигать поставленную задачу через методы Graphable

2023-10-23 05:10 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/Graphable.java
> +    StringBuilder shortestPaths(T vert);
то есть у тебя должна быть ОДНА реализация этого метода

2023-10-30 09:00 UTC, galinabykova requested changes

2023-10-30 09:00 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/Vertex.java
> +    public T object;
оборачивай поля в геттеры и сеттеры
https://javarush.com/groups/posts/1928-getterih-i-setterih
есть библиотечка, которая позволяет избавиться от шаблонного кода, такого, как геттеры-сеттеры
https://habr.com/ru/companies/piter/articles/676394/
Её использовать не требую

2023-10-30 09:00 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/Vertex.java
> +    public boolean equals(Object obj) {
если есть equals, должен быть hashcode

2023-10-30 09:00 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/Edge.java
> +    public Vertex<T> src;
не надо давать доступ к полю

2023-10-30 09:00 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/Edge.java
> +    public Vertex<T> dest;
тут тоже не надо давать публичный доступ к полю

2023-10-30 09:00 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/Edge.java
> +    public int weight;
тут тоже не надо давать публичный доступ к полю

2023-10-30 09:00 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/Edge.java
> +    public boolean equals(Object obj) {
нужен hashcode, если есть equals

2023-10-30 09:00 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/Edge.java
> +     * @param obj - object
лучше уточнить в спецификации, что такое "равные" рёбра в твоей библиотеке, если этот метод доступен пользователю твоей библиотеки

2023-10-30 09:00 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/Graph.java
> +    protected static final int inf = Integer.MAX_VALUE;
в google java style, который мы используем в нашем курсе, написано:
"Constant names use UPPER_SNAKE_CASE: all uppercase letters, with each word separated from the next by a single underscore...

Constants are static final fields... "

https://google.github.io/styleguide/javaguide.html

2023-10-30 09:00 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/Graph.java
> +        ArrayList<VertexDistance<T>> map = new ArrayList<>();
не очень понятно по названию, что это за переменная

2023-10-30 09:00 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/Graph.java
> +    public StringBuilder shortestPath(Vertex<T> vertex) {
этот метод не должен возвращать StringBuilder. Вдруг пользователь хочет дальше работать с отсортированным списком вершин? Парсить строчку будет больно

2023-10-30 09:00 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/GraphAdjacencyList.java
> +    public void addVertex(Vertex<T> vertex) {
используй аннотацию Override

2023-10-30 09:00 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/Graph.java
> +    public abstract void addVertex(Vertex<T> vertex);
во всех трёх реализациях, если вершина уже добавлена, этот метод ничего не делает. Это обсуждаемо, но, возможно, стоило бы как-то сообщить пользователю, была добавлена новая вершина или нет

2023-10-30 09:00 UTC, galinabykova commented on Task_1_2_2/src/test/java/ru/nsu/palkin/MainTest.java
в условии сказано, что "Для тестирования загружайте начальное состояние графов из текстового файла."

2023-10-31 06:03 UTC, galinabykova requested changes

2023-10-31 06:03 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/palkin/GraphAdjacencyList.java
> +    public int addVertex(Vertex<T> vertex) {
функция возвращает всего два значений 1 и -1. Может быть лучше использовать bool? и нужно описать в спецификации, что она возвращает

2023-10-31 08:43 UTC, galinabykova requested changes
пожалуйста, увеличь покрытие у файлов Edge и Vertex

2023-10-31 08:56 UTC, PalkinEgor commented
> пожалуйста, увеличь покрытие у файлов Edge и Vertex

У меня большую часть кода в этих классах занимает hashCode и геттеры и сеттеры, которые не используются. Мне нужно какой то еще тест для этих методов написать?

2023-10-31 09:05 UTC, galinabykova commented
> > пожалуйста, увеличь покрытие у файлов Edge и Vertex
> 
> У меня большую часть кода в этих классах занимает hashCode и геттеры и сеттеры, которые не используются. Мне нужно какой то еще тест для этих методов написать?
Добавь тогда только на hashCode, это важно, потому что это публичный класс, который могут использовать пользователи твоей библиотеки.  Для остального можно не делать

2023-10-31 09:21 UTC, galinabykova approved these changes

2023-10-31 10:53 UTC, merged