Task_1_3_1
PalkinEgor/OOP pull request #6
Opened 2023-11-07 20:57 UTC by PalkinEgor

2023-11-07 21:01 UTC, PalkinEgor commented
В этом решении пока есть некоторые проблемы, но надеюсь, что на мягкий дедлайн будет достаточно.
Проблемы:
1) Пока нет теста с большим файлом, но я локально проверил с маленьким буфером и все работает, значит с большим файлом все тоже должно работать.
2) Есть проблема с символами, которые занимают больше чем два байта. Эта проблема есть из-за того, что использую массивы чаров, а надо бы использовать строки.

2023-11-08 03:53 UTC, galinabykova requested changes
на мягкий дедлайн достаточно. Не затягивай с правками, после появления большого файлика, скорее всего, появятся замечания

2023-11-15 04:46 UTC, galinabykova requested changes

2023-11-15 04:46 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/palkin/MainTest.java
> +    public void largeTest() {
большой тест не должен быть закомментирован. Файлик в нём должен генерироваться, а не браться из репозитория ( потому что файл 15 ГБ очень большой, такие файлы лучше не хранить в репозитории). В конце теста этот файл нужно удалить

2023-11-15 10:16 UTC, galinabykova requested changes

2023-11-15 10:16 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/palkin/MainTest.java
> +        long fileLen = 50000000;
ещё можно будет писать 5_000_000, чтобы было более читаемо

2023-11-15 10:16 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/palkin/Search.java
> +            System.out.println(e.getMessage());
тут лучше бросить исключение, уточнив ошибку или вообще не ловить (тогда надо будет throws в сигнатуре написать)

2023-11-15 15:03 UTC, galinabykova approved these changes

2023-11-15 15:07 UTC, merged