Task_1_4_1
PalkinEgor/OOP pull request #7
Opened 2023-11-19 17:27 UTC by PalkinEgor

2023-11-20 11:06 UTC, galinabykova requested changes

2023-11-20 11:06 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/palkin/Student.java
> +            return "Surname: " + this.surname + "; Name: "
Небольшой теоретический вопрос: будет ли здесь создаваться StringBuilder?

2023-11-20 11:06 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/palkin/CreditBook.java
> +         * @param typeOfCredit - credit or exam
если всего два значения, лучше сделать Enum

2023-11-20 11:06 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/palkin/CreditBook.java
> +    public boolean redCertificate() {
в этой функции нужно по максимуму заменить циклы на StreamAPI. Это должно сделать код более читаемым, а ещё нужно, чтобы ты поразбирался со StreamAPI

2023-11-20 11:06 UTC, galinabykova commented on Task_1_4_1/src/test/java/ru/nsu/palkin/MainTest.java
кажется, у тебя не проверяется случай, когда у студента средний балл подходящий, но есть тройки

2023-11-20 15:05 UTC, PalkinEgor commented on Task_1_4_1/src/test/java/ru/nsu/palkin/MainTest.java
Проверяется 
![Снимок экрана 2023-11-20 220412](https://github.com/PalkinEgor/OOP/assets/98741919/f457db07-4cfe-4bbb-9317-7a581d212482)

2023-11-20 17:28 UTC, galinabykova commented on Task_1_4_1/src/test/java/ru/nsu/palkin/MainTest.java
криво сформулировала, имела ввиду, не проверяется в тестах

2023-11-21 16:53 UTC, PalkinEgor commented on Task_1_4_1/src/main/java/ru/nsu/palkin/Student.java
> +            return "Surname: " + this.surname + "; Name: "
Нет

2023-11-21 17:08 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/palkin/Student.java
> +            return "Surname: " + this.surname + "; Name: "
Она создаётся, вот так написано в документации:
The Java language provides special support for the string concatenation operator ( + ), and for conversion of other objects to strings. String concatenation is implemented through the StringBuilder(or StringBuffer) class and its append method. String conversions are implemented through the method toString, defined by Object and inherited by all classes in Java. For additional information on string concatenation and conversion, see Gosling, Joy, and Steele, The Java Language Specification.

Язык Java предоставляет специальную поддержку оператора конкатенации строк ( ) и преобразования других объектов в строки. Конкатенация строк реализуется с помощью класса StringBuilder(или StringBuffer) и его метода добавления. Преобразования строк реализуются с помощью метода toString, определенного Object и наследуемого всеми классами Java. Дополнительную информацию о конкатенации и преобразовании строк см. в статье Гослинг, Джой и Стил, Спецификация языка Java.
https://docs.oracle.com/javase/8/docs/api/java/lang/String.html

2023-11-21 17:32 UTC, galinabykova requested changes

2023-11-21 17:32 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/palkin/CreditBook.java
> +    public boolean redCertificate() {
попробуй тут совсем обойтись без for

2023-11-21 17:32 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/palkin/CreditBook.java
> +    public Term getTerm(int n) {
выглядит очень больно, может быть лучше сделать что-то такое
https://www.delftstack.com/howto/java/java-enum-to-int/ (пункт 4)
или
https://codingexplained.com/coding/java/enum-to-integer-and-integer-to-enum

2023-11-21 17:32 UTC, galinabykova commented on Task_1_4_1/src/test/java/ru/nsu/palkin/MainTest.java
> +    public void redCertificateFalse2Test() {
лучше сделать более осмысленное название (вместо False2)

2023-11-22 12:11 UTC, galinabykova requested changes
reviewdog

2023-11-23 11:01 UTC, galinabykova approved these changes

2023-11-23 11:10 UTC, merged