Task_1_5_1
PalkinEgor/OOP pull request #8
Opened 2023-12-04 08:33 UTC by PalkinEgor

2023-12-04 16:11 UTC, galinabykova requested changes

2023-12-04 16:11 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/palkin/Addition.java
> +            throw new RuntimeException("Stack is empty");
в этой задаче нужно построить свою иерархию исключений

2023-12-04 16:11 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/palkin/Addition.java
> +            throw new RuntimeException("Stack is empty");
то есть создать свои классы исключений

2023-12-04 16:11 UTC, galinabykova commented on Task_1_5_1/src/test/java/ru/nsu/palkin/MainTest.java
хочется отдельный "успешный" тест на каждую операцию (у тебя, кажется, нет такого на умножение и деление). Это простая операция, но в процессе поддержания кода, можно случайно что-то сломать, поэтому лучше прописать такие тесты. С делением, например, можно легко перепутать порядок чиселок.

2023-12-10 07:43 UTC, galinabykova requested changes

2023-12-10 07:43 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/palkin/Multiplication.java
> +            throw new RuntimeException();
здесь ты перехватываешь исключение и его же бросаешь, не добавляя никакой дополнительной информации

2023-12-10 07:43 UTC, galinabykova commented on Task_1_5_1/src/main/java/ru/nsu/palkin/Sin.java
> +            throw new RuntimeException("Stack is empty");
здесь ты добавил сообщение, так что это оправдано. Почему ты решил здесь бросать RuntimeException? Можно было, кстати, отнаследовать некоторые свои исключения от RuntimeException.

2023-12-10 14:41 UTC, PalkinEgor commented on Task_1_5_1/src/main/java/ru/nsu/palkin/Sin.java
> +            throw new RuntimeException("Stack is empty");
Использовал здесь runtime exception, так как считаю этот тип исключений (исключения, которые вызваны ошибками программирования, а не ожидаемыми в приложении) подходящим в данной ситуации. Например если мы ввели неправильное выражение или логику как то не так прописали.

2023-12-10 15:46 UTC, galinabykova approved these changes

2023-12-10 15:47 UTC, merged